In [1]:
import torch
import numpy as np
from torch import manual_seed

In [18]:
# 据已有数据创建张量
t1 = torch.tensor([1,2,3])
print(t1, t1.dtype)
# 创建一个空的张量
data = np.random.randn(2, 3)
t2 = torch.Tensor(data)
# 创建2x3的浮点型张量
t3 = torch.DoubleTensor(2, 3)
t4 = torch.empty(1, 1)
print(t2, t2.dtype)
print(t3)
print(t4)

tensor([1, 2, 3]) torch.int64
tensor([[ 0.4412, -0.8755, -0.6073],
        [ 0.2609, -0.6145, -0.2360]]) torch.float32
tensor([[1.0964e-311,  1.5184e+00,  6.3766e-01],
        [ 5.5828e-01,  5.9672e-01,  1.1690e+00]], dtype=torch.float64)
tensor([[8.4078e-45]])


In [28]:
# 创建线性张量

t5 = torch.arange(0, 10, 2)
t6 = torch.linspace(0, 1, steps=5)
print(t5)
print(t6)

tensor([0, 2, 4, 6, 8])
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


In [40]:
# 创建随机张量
print(torch.random.initial_seed())
# 设置随机种子
torch.random.manual_seed(100)
print(torch.random.initial_seed())
t7 = torch.randn(2, 3)
print(t7)
t8 = torch.randn(2, 3)
print(t8)

100
100
tensor([[-2.3652, -0.8047,  0.6587],
        [-0.2586, -0.2510,  0.4770]])
tensor([[-0.5883, -0.6131,  0.4322],
        [ 0.4612, -0.9014, -0.2675]])


In [45]:
# 0, 1张量
t9 = torch.zeros(2, 3)
t10 = torch.ones(2, 3)
# 创建指定形状的张量
t11 = torch.zeros_like(t10)
# 创建指定形状的常数张量
t12 = torch.full_like(t10, 200)
print(t9, t9.dtype)
print(t10, t10.dtype)
print(t11, t11.dtype)
print(t12, t12.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) torch.float32
tensor([[1., 1., 1.],
        [1., 1., 1.]]) torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.]]) torch.float32
tensor([[200., 200., 200.],
        [200., 200., 200.]]) torch.float32


In [54]:
# 张量类型转换
t13 = torch.full([2, 3], 10)
print(t13, t13.dtype)
t14 = t13.type(torch.DoubleTensor)  # 转换为浮点型张量,返回新的张量
print(t14)
t15 = t13.double()   # 转换为浮点型张量,返回新的张量
print(t15)

tensor([[10, 10, 10],
        [10, 10, 10]]) torch.int64
tensor([[10., 10., 10.],
        [10., 10., 10.]], dtype=torch.float64)
tensor([[10., 10., 10.],
        [10., 10., 10.]], dtype=torch.float64)


In [66]:
# 张量基本计算
# 1. 基本计算
t1 = torch.randint(0, 10, [2, 3]).cuda()   # 随机生成一个2x3, 在0-10区间的矩阵
t1.add_(10) # 原地+10
t1.mul(0)   # 返回*0的新张量


tensor([[0, 0, 0],
        [0, 0, 0]], device='cuda:0') torch.int64


In [85]:
# 2. 阿达玛乘
# mul 函数 or *
t1 = torch.tensor([[1, 2], [3, 4]])  # 指定在GPU上创建张量
t2 = torch.tensor([[5, 6], [7, 8]])
#t3 = t1.mul(t2)
t3 = t1 * t2
t3


tensor([[ 5, 12],
        [21, 32]])

In [77]:
# 3. 点积运算
# @ or matmul
# mm    对二维
# bmm   对三维
t1 = torch.tensor([[1, 2], [3, 4], [5, 6]])
t2 = torch.tensor([[5, 6], [7, 8]])
t3 = t1 @ t2    # cuda 不支持整型运算
t3



tensor([[19, 22],
        [43, 50],
        [67, 78]])

In [88]:
t4 = torch.randn(3, 4, 5).cuda(device=0)    # 3批, 5行, 6列的张量
t5 = torch.randn(   5, 6).cuda(0)
t6 = t4 @ t5
t6.shape

torch.Size([3, 4, 6])

In [4]:
# 张量转numpy, 默认共享内存: 修改numpy也会修改torch
t1 = torch.tensor([1, 2, 3])
t1_np = t1.numpy().copy()   # 创建新的numpy, 不共享内存




tensor([1, 2, 3])


In [11]:
# numpy转Tensor: from_numpy 默认共享内存
t2_np = np.arange(0, 10)
t2 = torch.from_numpy(t2_np)
t3 = torch.tensor(t2_np)    # Tensor默认不共享内存
t2_np[0] = 100
t2, t3

(tensor([100,   1,   2,   3,   4,   5,   6,   7,   8,   9]),
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 torch.int64)

In [16]:
#标量张量和数字的转换
t4 = torch.tensor(10)   # 创建一个标量张量
t5 = torch.tensor([10])
t6 = torch.tensor([[30]])
print(t4.shape, t5.shape, t6.shape)

print(t4.item(), t5.item(), t6.item())  # 张量仅含1个元素, 可以用item()获取
print(t4.data, t5.data, t6.data)

torch.Size([]) torch.Size([1]) torch.Size([1, 1])
10 10 30
tensor(10) tensor([10]) tensor([[30]])


In [37]:
# 张量拼接 
# cat: 按维拼接
torch.manual_seed(0)    # 设置随机种子
t1 = torch.randint(0, 10, [3, 4, 5])
t2 = torch.randint(0, 10, [3, 4, 5])

# 1. 按维拼接
t3 = torch.cat([t1, t2], dim=0)
t4 = torch.cat([t1, t2], dim=1)
t5 = torch.cat([t1, t2], dim=2)

t3, t4, t5



(tensor([[[4, 9, 3, 0, 3],
          [9, 7, 3, 7, 3],
          [1, 6, 6, 9, 8],
          [6, 6, 8, 4, 3]],
 
         [[6, 9, 1, 4, 4],
          [1, 9, 9, 9, 0],
          [1, 2, 3, 0, 5],
          [5, 2, 9, 1, 8]],
 
         [[8, 3, 6, 9, 1],
          [7, 3, 5, 2, 1],
          [0, 9, 3, 1, 1],
          [0, 3, 6, 6, 7]],
 
         [[9, 6, 3, 4, 5],
          [0, 8, 2, 8, 2],
          [7, 5, 0, 0, 8],
          [1, 9, 6, 1, 0]],
 
         [[2, 9, 4, 3, 9],
          [3, 9, 3, 9, 8],
          [5, 3, 2, 8, 5],
          [6, 6, 5, 7, 2]],
 
         [[5, 6, 6, 5, 4],
          [0, 8, 1, 7, 8],
          [5, 4, 4, 8, 4],
          [4, 9, 0, 7, 4]]]),
 tensor([[[4, 9, 3, 0, 3],
          [9, 7, 3, 7, 3],
          [1, 6, 6, 9, 8],
          [6, 6, 8, 4, 3],
          [9, 6, 3, 4, 5],
          [0, 8, 2, 8, 2],
          [7, 5, 0, 0, 8],
          [1, 9, 6, 1, 0]],
 
         [[6, 9, 1, 4, 4],
          [1, 9, 9, 9, 0],
          [1, 2, 3, 0, 5],
          [5, 2, 9, 1, 8],
       

In [36]:
# stack: 按维叠加

torch.manual_seed(0)

t1 = torch.randint(0, 10, [2, 3])
t2 = torch.randint(0, 10, [2, 3])

t3 = torch.stack([t1, t2], dim=0)
t4 = torch.stack([t1, t2], dim=1)
t5 = torch.stack([t1, t2], dim=2)

t6 = torch.cat([t1, t2], dim=0)

t3, t6

(tensor([[[4, 9, 3],
          [0, 3, 9]],
 
         [[7, 3, 7],
          [3, 1, 6]]]),
 tensor([[4, 9, 3],
         [0, 3, 9],
         [7, 3, 7],
         [3, 1, 6]]))

In [41]:
# 张量索引

torch.manual_seed(0)
t = torch.randint(0, 10, [4, 5])
print(t)


tensor([[4, 9, 3, 0, 3],
        [9, 7, 3, 7, 3],
        [1, 6, 6, 9, 8],
        [6, 6, 8, 4, 3]])


In [43]:
# 1. 简单行、列索引
print(t[0])
print(t[:, 0])

tensor([4, 9, 3, 0, 3])
tensor([4, 9, 1, 6])


In [53]:
# 2. 列表索引
print(t[[0, 1], [1, 2]])    # 返回 (0, 1)、(1, 2) 两个位置的元素
print(t[[[0], [1]], [1, 2]])# 返回 0、1 行的 1、2 列共4个元素

tensor([9, 3])
tensor([[9, 3],
        [7, 3]])


In [47]:
# 3. 范围索引
print(t[:3, :2]) # 前3行的前2列数据
print(t[2:, :2]) # 第2行到最后的前2列数据

tensor([[4, 9],
        [9, 7],
        [1, 6]])
tensor([[1, 6],
        [6, 6]])


In [49]:
# 4. bool 索引
print(t[t[:, 2] > 5]) # 第3列大于5的行数据
print(t[:, t[1] > 5]) # 第2行大于5的列数据

tensor([[1, 6, 6, 9, 8],
        [6, 6, 8, 4, 3]])
tensor([[4, 9, 0],
        [9, 7, 7],
        [1, 6, 9],
        [6, 6, 4]])


In [57]:
# 5. 多维索引 
t_ = torch.randint(0, 10, [3, 4, 5])
print(t_)

tensor([[[9, 8, 5, 6, 4],
         [3, 3, 4, 0, 2],
         [5, 1, 2, 8, 2],
         [4, 8, 3, 6, 5]],

        [[8, 8, 0, 5, 1],
         [3, 0, 8, 1, 1],
         [1, 7, 2, 2, 2],
         [3, 3, 6, 7, 8]],

        [[0, 5, 0, 3, 5],
         [5, 3, 6, 2, 2],
         [5, 5, 9, 4, 3],
         [3, 7, 3, 8, 0]]])


In [58]:
print(t_[0, :, :])
print(t_[:, 0, :])
print(t_[:, :, 0])

tensor([[9, 8, 5, 6, 4],
        [3, 3, 4, 0, 2],
        [5, 1, 2, 8, 2],
        [4, 8, 3, 6, 5]])
tensor([[9, 8, 5, 6, 4],
        [8, 8, 0, 5, 1],
        [0, 5, 0, 3, 5]])
tensor([[9, 3, 5, 4],
        [8, 3, 1, 3],
        [0, 5, 5, 3]])
